### ISSUE TITLE
change currency in haiwai versions' shop

### ISSUE THREAD

**Issue by custom-ivan** [custom-ivan/dota_card_war#13]
![image](https://user-images.githubusercontent.com/3997243/126723046-1880dd7d-bfba-4bcc-a05e-2fbaa417f53e.png)
![image](https://user-images.githubusercontent.com/3997243/126723062-749ccf48-d2f8-41c7-84fa-46e697725a8c.png)

**Comment by StarSoulStudio** [comment]
fixed
