### ISSUE TITLE
english translation generally reads as clunky

### ISSUE THREAD

**Issue by definitely-kyle** [custom-ivan/dota_card_war#26]
Most tooltips have a grammar/flow error. For example "chess will return to the chess pool when commander failed" should probably read "heroes will return to the hero pool when a commander dies".

The word "composited" is used where "combined" should probably be used.

I'm compiling a list of more translation changes which could be made to make text easier to read for english-speaking players.

**Comment by definitely-kyle** [comment]
For example a possible Tutorial Tab rewrite could be:
------------------------------
Tutorial
A. Buying Chess Pieces
* It costs 3 Dota Coins to purchase a chess piece
* Drag pieces to your hero to buy them
* Your amount of Dota Coins is shown in the bottom right corner

B. Commanders and Skills
* Both passive skills and active skills can be useful
* Active skills can only be used once per turn, whereas passive skills are always in effect

C. The Shop (Purchase Area)
* The Shop automatically refreshes with new pieces each turn
* The Shop can also be refreshed manually for 1 Dota Coin
* To the left of your commander are the [Upgrade], [Freeze] and [Refresh] Buttons

D. Combining Chess Pieces and Bonuses
* 3 of the same piece can be combined into a golden copy which increased stats
* You also receive a bonus reward, which lets you discover a card which is 1 star higher than your commander level

E. Battle Rules
* Your opponents are shown on the left bar
* Pieces attack from left to right
* Attack targets are random, but pieces with Taunt will be attacked first

F. Damage Rules
* The winner of the battle will deal damage to the loser
* Battle damage is equal to the sum of your commander level and remaining pieces' total stars

**Comment by custom-ivan** [comment]
to-do

**Comment by StarSoulStudio** [comment]
fixed

**Comment by StarSoulStudio** [comment]
update 8.3
