### ISSUE TITLE
Nerf Tombs!

### ISSUE THREAD

**Issue by takron** [custom-ivan/dota_card_war#28]
I think that it is necessary to change the effect of the ghoul (2 stars creature), which infects the entire enemy table with venom, because at the moment there is no effective way to deal with the tombs. Often a necrolord, necrophos and undying are assembled for this combination. Even if we assume that there is a creature from the 6th star that can easily kill a necrolord, the undying will still be able to resurrect him with a 90% probability. At the moment, this combination copes with absolutely all stats and divine shields, and in addition, the undying can easily deal with all summoned creatures alone.
**Example of change:** Ghoul's effect: deathrattle - hits 2 random enemy creatures with venom 1.
**Golden version:** hits 2 random enemy creatures with venom 2.

**Comment by custom-ivan** [comment]
yes, i myself heard multiple reports of that tombs are too OP. 

nerf.

**Comment by StarSoulStudio** [comment]
We update today:
*Adjust the effect of the 2-star Tomb chess Ghoul death rattle from Poisoning 1 for all to Poisoning 1 for 2 units randomly;
