### ISSUE TITLE
interface elements displaying over dota ping/fps meter

### ISSUE THREAD

**Issue by custom-ivan** [custom-ivan/dota_card_war#5]
![image](https://user-images.githubusercontent.com/3997243/126422879-f3336d83-ea32-420d-bf59-88d737c1d977.png)

Possible solution: place UI elements properly

**Comment by custom-ivan** [comment]
picrelated:
![image](https://user-images.githubusercontent.com/3997243/126519128-1b218a66-4cfa-4dc0-9edf-d1442ca3aa70.png)

**Comment by StarSoulStudio** [comment]
Our producer says that is not a problem:)
